// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: api/service/network/v1/network.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// NetworkServiceClient is the client API for NetworkService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NetworkServiceClient interface {
	GetInterface(ctx context.Context, in *GetInterfaceRequest, opts ...grpc.CallOption) (*Interface, error)
	ListInterfaces(ctx context.Context, in *ListInterfacesRequest, opts ...grpc.CallOption) (*ListInterfacesResponse, error)
	WifiConnect(ctx context.Context, in *WifiConnectRequest, opts ...grpc.CallOption) (*WifiConnectResponse, error)
	WifiConnectConfirm(ctx context.Context, in *WifiConnectConfirmRequest, opts ...grpc.CallOption) (*WifiConnectConfirmResponse, error)
	WifiScan(ctx context.Context, in *WifiScanRequest, opts ...grpc.CallOption) (*WifiScanResponse, error)
}

type networkServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNetworkServiceClient(cc grpc.ClientConnInterface) NetworkServiceClient {
	return &networkServiceClient{cc}
}

func (c *networkServiceClient) GetInterface(ctx context.Context, in *GetInterfaceRequest, opts ...grpc.CallOption) (*Interface, error) {
	out := new(Interface)
	err := c.cc.Invoke(ctx, "/acme.service.network.v1.NetworkService/GetInterface", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkServiceClient) ListInterfaces(ctx context.Context, in *ListInterfacesRequest, opts ...grpc.CallOption) (*ListInterfacesResponse, error) {
	out := new(ListInterfacesResponse)
	err := c.cc.Invoke(ctx, "/acme.service.network.v1.NetworkService/ListInterfaces", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkServiceClient) WifiConnect(ctx context.Context, in *WifiConnectRequest, opts ...grpc.CallOption) (*WifiConnectResponse, error) {
	out := new(WifiConnectResponse)
	err := c.cc.Invoke(ctx, "/acme.service.network.v1.NetworkService/WifiConnect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkServiceClient) WifiConnectConfirm(ctx context.Context, in *WifiConnectConfirmRequest, opts ...grpc.CallOption) (*WifiConnectConfirmResponse, error) {
	out := new(WifiConnectConfirmResponse)
	err := c.cc.Invoke(ctx, "/acme.service.network.v1.NetworkService/WifiConnectConfirm", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkServiceClient) WifiScan(ctx context.Context, in *WifiScanRequest, opts ...grpc.CallOption) (*WifiScanResponse, error) {
	out := new(WifiScanResponse)
	err := c.cc.Invoke(ctx, "/acme.service.network.v1.NetworkService/WifiScan", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NetworkServiceServer is the server API for NetworkService service.
// All implementations must embed UnimplementedNetworkServiceServer
// for forward compatibility
type NetworkServiceServer interface {
	GetInterface(context.Context, *GetInterfaceRequest) (*Interface, error)
	ListInterfaces(context.Context, *ListInterfacesRequest) (*ListInterfacesResponse, error)
	WifiConnect(context.Context, *WifiConnectRequest) (*WifiConnectResponse, error)
	WifiConnectConfirm(context.Context, *WifiConnectConfirmRequest) (*WifiConnectConfirmResponse, error)
	WifiScan(context.Context, *WifiScanRequest) (*WifiScanResponse, error)
	mustEmbedUnimplementedNetworkServiceServer()
}

// UnimplementedNetworkServiceServer must be embedded to have forward compatible implementations.
type UnimplementedNetworkServiceServer struct {
}

func (UnimplementedNetworkServiceServer) GetInterface(context.Context, *GetInterfaceRequest) (*Interface, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInterface not implemented")
}
func (UnimplementedNetworkServiceServer) ListInterfaces(context.Context, *ListInterfacesRequest) (*ListInterfacesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListInterfaces not implemented")
}
func (UnimplementedNetworkServiceServer) WifiConnect(context.Context, *WifiConnectRequest) (*WifiConnectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WifiConnect not implemented")
}
func (UnimplementedNetworkServiceServer) WifiConnectConfirm(context.Context, *WifiConnectConfirmRequest) (*WifiConnectConfirmResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WifiConnectConfirm not implemented")
}
func (UnimplementedNetworkServiceServer) WifiScan(context.Context, *WifiScanRequest) (*WifiScanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WifiScan not implemented")
}
func (UnimplementedNetworkServiceServer) mustEmbedUnimplementedNetworkServiceServer() {}

// UnsafeNetworkServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NetworkServiceServer will
// result in compilation errors.
type UnsafeNetworkServiceServer interface {
	mustEmbedUnimplementedNetworkServiceServer()
}

func RegisterNetworkServiceServer(s grpc.ServiceRegistrar, srv NetworkServiceServer) {
	s.RegisterService(&NetworkService_ServiceDesc, srv)
}

func _NetworkService_GetInterface_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInterfaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkServiceServer).GetInterface(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/acme.service.network.v1.NetworkService/GetInterface",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkServiceServer).GetInterface(ctx, req.(*GetInterfaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkService_ListInterfaces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListInterfacesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkServiceServer).ListInterfaces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/acme.service.network.v1.NetworkService/ListInterfaces",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkServiceServer).ListInterfaces(ctx, req.(*ListInterfacesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkService_WifiConnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WifiConnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkServiceServer).WifiConnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/acme.service.network.v1.NetworkService/WifiConnect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkServiceServer).WifiConnect(ctx, req.(*WifiConnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkService_WifiConnectConfirm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WifiConnectConfirmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkServiceServer).WifiConnectConfirm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/acme.service.network.v1.NetworkService/WifiConnectConfirm",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkServiceServer).WifiConnectConfirm(ctx, req.(*WifiConnectConfirmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkService_WifiScan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WifiScanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkServiceServer).WifiScan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/acme.service.network.v1.NetworkService/WifiScan",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkServiceServer).WifiScan(ctx, req.(*WifiScanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NetworkService_ServiceDesc is the grpc.ServiceDesc for NetworkService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NetworkService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "acme.service.network.v1.NetworkService",
	HandlerType: (*NetworkServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInterface",
			Handler:    _NetworkService_GetInterface_Handler,
		},
		{
			MethodName: "ListInterfaces",
			Handler:    _NetworkService_ListInterfaces_Handler,
		},
		{
			MethodName: "WifiConnect",
			Handler:    _NetworkService_WifiConnect_Handler,
		},
		{
			MethodName: "WifiConnectConfirm",
			Handler:    _NetworkService_WifiConnectConfirm_Handler,
		},
		{
			MethodName: "WifiScan",
			Handler:    _NetworkService_WifiScan_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/service/network/v1/network.proto",
}
